# Generated by Django 5.2.1 on 2025-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_mode',
            field=models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('CHEQUE', 'CHEQUE'), ('CASH', 'CASH'), ('OTHER', 'OTHER')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_head',
            field=models.CharField(choices=[('ADVANCE', 'ADVANCE'), ('REIMBURSEMENT', 'REIMBURSEMENT'), ('ELECTRICITY', 'Electricity Bill'), ('REMUNERATION_TEACHERS', 'Teachers Remuneration'), ('SALARIES_STAFF', 'Staff Salaries'), ('MAINTENANCE_BUILDING', 'Building Maintenance'), ('LIBRARY_BOOKS', 'Library Books/Resources'), ('LAB_EQUIPMENT', 'Lab Equipment Purchase'), ('SPORTS_EQUIPMENT', 'Sports Equipment'), ('HOSTEL_EXPENSES', 'Hostel Operations/Maintenance'), ('ADVERTISING_MARKETING', 'Advertising & Marketing'), ('STUDENT_WELFARE', 'Student Welfare Activities'), ('UTILITIES_WATER', 'Water Bill'), ('TELEPHONE_INTERNET', 'Telephone & Internet Bills'), ('TRANSPORTATION', 'Transportation Costs'), ('EXAM_FEES_COLLECTION', 'Exam Fees Collection'), ('ADMISSION_FEES_COLLECTION', 'Admission Fees Collection'), ('DONATIONS_RECEIVED', 'Donations Received'), ('BANK_INTEREST_EARNED', 'Bank Interest Earned'), ('VENDOR_PAYMENT_SUPPLIES', 'Vendor Payment - Office Supplies'), ('SECURITY_SERVICES', 'Security Services'), ('AUDIT_FEES', 'Audit Fees'), ('SCHOLARSHIPS_DISBURSED', 'Scholarships Disbursed'), ('CULTURAL_EVENTS', 'Cultural Event Expenses'), ('SPORTS_EVENTS', 'Sports Event Expenses'), ('RENT_RECEIVED', 'Rent Received (Property/Facilities)'), ('SEMINARS_WORKSHOPS', 'Seminars & Workshops Expenses'), ('RESEARCH_GRANTS_RECEIVED', 'Research Grants Received'), ('BANK_CHARGES', 'Bank Charges/Fees'), ('STUDENT_FEES_TUITION', 'Student Tuition Fees'), ('EQUIPMENT_REPAIR', 'Equipment Repair & Servicing'), ('UNIFORM_PURCHASE', 'Uniform Purchase'), ('PRINTING_STATIONERY', 'Printing & Stationery'), ('GOVT_GRANTS_RECEIVED', 'Government Grants Received'), ('TAX_PAYMENTS', 'Tax Payments'), ('LOAN_REPAYMENT', 'Loan Repayment (Principal & Interest)'), ('CONSTRUCTION_EXPENSES', 'New Construction/Renovation'), ('OTHERS', 'OTHERS')], max_length=50),
        ),
    ]
