# Generated by Django 5.2.1 on 2025-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_alter_bankaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
