# Generated by Django 5.2.1 on 2025-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0004_transaction_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_head',
            field=models.CharField(choices=[('ADMISSION_FEES_COLLECTION', 'Admission Fees Collection'), ('ADVANCE', 'ADVANCE'), ('ADVERTISING_MARKETING', 'Advertising & Marketing'), ('AUDIT_FEES', 'Audit Fees'), ('BANK_CHARGES', 'Bank Charges/Fees'), ('BANK_INTEREST_EARNED', 'Bank Interest Earned'), ('CONSTRUCTION_EXPENSES', 'New Construction/Renovation'), ('CULTURAL_EVENTS', 'Cultural Event Expenses'), ('DONATIONS_RECEIVED', 'Donations Received'), ('ELECTRICITY', 'Electricity Bill'), ('EQUIPMENT_REPAIR', 'Equipment Repair & Servicing'), ('EXAM_FEES_COLLECTION', 'Exam Fees Collection'), ('GOVT_GRANTS_RECEIVED', 'Government Grants Received'), ('HOSTEL_EXPENSES', 'Hostel Operations/Maintenance'), ('LAB_EQUIPMENT', 'Lab Equipment Purchase'), ('LIBRARY_BOOKS', 'Library Books/Resources'), ('LOAN_REPAYMENT', 'Loan Repayment (Principal & Interest)'), ('MAINTENANCE_BUILDING', 'Building Maintenance'), ('OTHERS', 'OTHERS'), ('PRINTING_STATIONERY', 'Printing & Stationery'), ('REIMBURSEMENT', 'REIMBURSEMENT'), ('REMUNERATION_TEACHERS', 'Teachers Remuneration'), ('RENT_RECEIVED', 'Rent Received (Property/Facilities)'), ('RESEARCH_GRANTS_RECEIVED', 'Research Grants Received'), ('SALARIES_STAFF', 'Staff Salaries'), ('SCHOLARSHIPS_DISBURSED', 'Scholarships Disbursed'), ('SECURITY_SERVICES', 'Security Services'), ('SEMINARS_WORKSHOPS', 'Seminars & Workshops Expenses'), ('SPORTS_EQUIPMENT', 'Sports Equipment'), ('SPORTS_EVENTS', 'Sports Event Expenses'), ('STUDENT_FEES_TUITION', 'Student Tuition Fees'), ('STUDENT_WELFARE', 'Student Welfare Activities'), ('TAX_PAYMENTS', 'Tax Payments'), ('TELEPHONE_INTERNET', 'Telephone & Internet Bills'), ('TRANSPORTATION', 'Transportation Costs'), ('UNIFORM_PURCHASE', 'Uniform Purchase'), ('UTILITIES_WATER', 'Water Bill')], max_length=50),
        ),
    ]
