# Generated by Django 5.2.1 on 2025-06-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0005_alter_transaction_transaction_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_pp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
